+ backup settting based on sections in sections.conf

diff --git a/gnome/gnome_conf b/gnome/gnome_conf
--- a/gnome/gnome_conf
+++ b/gnome/gnome_conf
@@ -8,17 +8,47 @@ if set -ql _flag_h
     echo "$usage" >&2
     return 1
 end
-for arg in $argv
-    switch $arg
+if test (count $argv) -eq 0
+    echo "$usage" >&2
+    return 1
+end
+
+set main_dir ~/dotfiles/gnome
+set config_file $main_dir/sections.conf
+set backup_dir $main_dir/settings
+# Function: process_paths
+# Description: Reads a config file and outputs "section_path [TAB] filename.ini"
+function process_paths
+    set -l config_file ~/dotfiles/gnome/sections.conf
+
+    # if not test -f "$config_file"
+    #     echo "Error: File '$config_file' not found." >&2
+    #     return 1
+    # end
+
+    cat "$config_file" -p | while read -l line
+        # Clean the line and skip comments/empty space
+        set -l clean_line (string trim $line)
+        if test -z "$clean_line"; or string match -q "#*" "$clean_line"
+            continue
+        end
+
+        # Generate the filename
+        set -l filename (string trim --chars=/ $clean_line | string replace --all '/' '_').ini
+
+        # Return both values separated by a tab
+        echo -e "$clean_line\t$filename"
+    end
+end
+
+# Capture the function output and iterate through the pairs
+process_paths | while read -l -d \t section backup_file
+    switch $argv[1]
         case backup
-            echo backup gnome settings
-            dconf dump /org/gnome/shell/extensions/ >~/dotfiles/gnome/org_gnome_shell_extensions.ini
-            dconf dump /org/gnome/desktop/wm/keybindings/ >~/dotfiles/gnome/org_gnome_desktop_wm_keybindings.ini
+            echo "backup $section into $backup_dir/$backup_file"
+            dconf dump $section >$backup_dir/$backup_file
         case restore
-            echo restore
-            dconf load /org/gnome/shell/extensions/ <~/dotfiles/gnome/org_gnome_shell_extensions.ini
-            dconf load /org/gnome/desktop/wm/keybindings/ <~/dotfiles/gnome/org_gnome_desktop_wm_keybindings.ini
-        case '*'
-            echo "$usage"
+            echo "restore $section from $backup_dir/$backup_file"
+            dconf load $section <$backup_dir/$backup_file
     end
 end
